services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app  
      - /usr/src/app/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - backend
    networks:
      - app-network


  backend:
    build:
      context: ./back
    ports:
      - "5001:5001"
    volumes:
      - ./back:/usr/src/app  
    environment:
      - FLASK_ENV=development  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
