services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./back
    ports:
      - "5000:5000"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

