services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app  
      - /usr/src/app/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./back
    ports:
      - "5001:5001"
    volumes:
      - ./back:/usr/src/app
      - ./data:/usr/src/app/data  # SQLiteデータベースの永続化
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - app-network
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5001"

networks:
  app-network:
    driver: bridge